- name: Redis
  hosts: all
  become: yes
  become_method: sudo
  gather_facts: True

  vars_prompt:
    - name: 'redis_version_selection'
      prompt: "\nPlease choose the number for Redis version [ 1/2/3/4/5/6] \n\n
      1: Redis2.8\n
      2: Redis3.0\n
      3: Redis3.2\n
      4: Redis4.0\n
      5: Redis5.0\n
      6: Redis6.0\n
      7: Redis-Latest\n"
      private: no
      default: 6
      
    - name: 'redis_insight_selection'
      prompt: "\nDon you want to install GUI tool RedisInsight? [ 1/2] \n\n
      1: Yes, install RedisInsight \n
      2: No, don't install RedisInsight\n"
      private: no
      default: 2
      
  vars:
    redis_version_select:
      '1': '2.8'
      '2': '3.0'
      '3': '3.2'
      '4': '4.0'
      '5': '5.0'
      '6': '6.0'
      '7': 'stable'
      
    redis_insight_select:
      '1': True
      'y': True
      '2': False
      'n': False
      
    redis_version: "{{redis_version_select[redis_version_selection]}}" 
    redis_install_redisinsight: "{{redis_insight_select[redis_insight_selection]}}" 
  
  vars_files:
    - vars/main.yml

  roles:
    - {role: role_common, tags: "role_common"}  
    - {role: role_cloud, tags: "role_cloud"}  
    - {role: role_nginx, tags: "role_nginx", when: redis_install_redisinsight}  
    - {role: role_redis, tags: "role_redis"}
    - {role: role_init, tags: "role_init"} 
    - {role: role_preend, tags: "role_preend"}
    - {role: role_end, tags: "role_end"}
